name: tmcr-newlogic-lib
version: 0.1.0
author: "Ibot02"
maintainer: "jtp.jtp@gmx.de"
extra-source-files:
 - README.md
library:
  source-dirs:
   - src/
  dependencies:
   - base
   - lens
   - containers
   - transformers
   - megaparsec
